### ISSUE TITLE
Support overriding the operationName

### ISSUE THREAD

**Issue by challgren** [softonic/graphql-client#18]
When sending the request to the server we should allow for someone to override the operationName

**Comment by rccrdpccl** [comment]
What do you mean by overriding the operationName? Aren't you able to set the operation name, as in test https://github.com/softonic/graphql-client/blob/master/tests/ClientTest.php#L172 ?

**Comment by challgren** [comment]
For multiple queries in the same transaction the API I'm querying requires
an operationName parameter to be sent since there's 2 or more queries

**Comment by challgren** [comment]
After my discussion with the stakeholders of the API this is really only a client side thing that isn't returned in their API and not required.
