### ISSUE TITLE
Uploading file to GraphQL API

### ISSUE THREAD

**Issue by timbertens** [softonic/graphql-client#20]
Is there any way to upload files to a GraphQL API using this package?

**Comment by timbertens** [comment]
see pull request https://github.com/softonic/graphql-client/pull/21

**Comment by joskfg** [comment]
As we talked in the PR, the [upload file spec](https://github.com/jaydenseric/graphql-multipart-request-spec) is not official (not even in the 20 nov draft).

If there are people interested in colaborate with a PR based in the spec, we could release some experimental branch for that feature not officially supported.
