### ISSUE TITLE
I can use mutations?

### ISSUE THREAD

**Issue by juanitourquiza** [softonic/graphql-client#25]
I need execution this code:

```
mutation($input: OBT_MOTIVOS_VIAJEEntry!) {
  createOBT_MOTIVO_VIAJE(input: $input) {
    NOMBRE_TIPO_MOTIVO,
    DESCRIPCION_TIPO_MOTIVO
  }
}
```

Variables:
```
{
  "input": {
    "NOMBRE_TIPO_MOTIVO": "mutPE",
    "DESCRIPCION_TIPO_MOTIVO": "mutPE",
    "DIRECCION_IP": "localhost"
  }
}
   
```

Is possible?

**Comment by joskfg** [comment]
Sure, you just need to do the request with your mutation as a gql string and set your variables as an array.

Based on your example:
```
$mutation =<<<'GQL'
mutation($input: OBT_MOTIVOS_VIAJEEntry!) {
  createOBT_MOTIVO_VIAJE(input: $input) {
    NOMBRE_TIPO_MOTIVO,
    DESCRIPCION_TIPO_MOTIVO
  }
}
GQL;

$variables = [
  "input" => [
    "NOMBRE_TIPO_MOTIVO" => "mutPE",
    "DESCRIPCION_TIPO_MOTIVO" => "mutPE",
    "DIRECCION_IP" => "localhost",
  ],
];


$response = $this->graphql->query($mutation, $variables);
```

EDIT: Added example in the README (#26)

**Comment by juanitourquiza** [comment]
Thanks, it's perfect. I just had to make a change:
`$response = $client->query($mutation, $variables);`

> Sure, you just need to do the request with your mutation as a gql string and set your variables as an array.
> 
> Based on your example:
> 
> ```
> $mutation =<<<'GQL'
> mutation($input: OBT_MOTIVOS_VIAJEEntry!) {
>   createOBT_MOTIVO_VIAJE(input: $input) {
>     NOMBRE_TIPO_MOTIVO,
>     DESCRIPCION_TIPO_MOTIVO
>   }
> }
> GQL;
> 
> $variables = [
>   "input" => [
>     "NOMBRE_TIPO_MOTIVO" => "mutPE",
>     "DESCRIPCION_TIPO_MOTIVO" => "mutPE",
>     "DIRECCION_IP" => "localhost",
>   ],
> ];
> 
> 
> $response = $this->graphql->query($mutation, $variables);
> ```
> 
> EDIT: Added example in the README (#26)
