### ISSUE TITLE
Feature: Response class implements Psr\Http\Message\ResponseInterface

### ISSUE THREAD

**Issue by 4n70w4** [softonic/graphql-client#28]
For compatibility with other client libraries.

For example, `Guzzle` uses this interface, and your library uses `Guzzle` as a transport. It would be logical to give the `Response` as a `ResponseInterface`. Or are there special reasons for not doing this?

**Comment by rccrdpccl** [comment]
`Response` class is a GraphQL response, not an HTTP response (although at the moment transport is only implemented in HTTP, in the future we might also use other underlying protocols). I don't see clearly how/if we could benefit by implementing `ResponseInterface`, do you have a specific example in mind?

**Comment by 4n70w4** [comment]
@rccrdpccl For example, I have a system that works with `ResponseInterface` abstraction. For your library, I have to do a separate hierarchy of abstractions for the whole system.

**Comment by rccrdpccl** [comment]
Thanks for getting back to me. Although I understand you have some generic system where you'd like to plug in our library, I am unable to imagine a scenario where GraphQL Response would benefit from being coupled to its transport. Could you please be a bit more specific? As you surely know, we let customize transport by letting inject HTTP client within the GraphQL client.

**Comment by 4n70w4** [comment]
@rccrdpccl For example, I log all requests and responses from client libraries. And I already have infrastructure working with `Psr\Http\Message\ResponseInterface`.

It is not rational to do logging support for custom response classes of each library. Why then come up with a `PSR`?

**Comment by rccrdpccl** [comment]
Would it be best logging the HTTP request that is already available through the injected http client (guzzle) in this case? Maybe with a middleware or some other strategy. I would be happy to add extensibility in that direction if it's missing any. What do you think?

The rationale is that GraphQL is a query language sitting on top of transport, and although the library is currently coupled with HTTP, we might support other transport mechanisms in the future, and the less we couple to transport the better. I would agree that we might seek standardisation for the response, but I still cannot see the advantage of coupling GraphQL response directly with HTTP interface. Internally, we should support the PSR that you have been suggesting for transport.
