### ISSUE TITLE
Where to provide headers?

### ISSUE THREAD

**Issue by Zeshan316** [softonic/graphql-client#32]
I am using this example **To instantiate a client without OAuth2**, but here i want to send headers what is the way?

**Receiving this error:** resulted in a `415 Unsupported Media Type` response

**Comment by Zeshan316** [comment]
I have figure out with headers but getting resulted in a `403 Forbidden` response.
Can you please help for this issue.

**Comment by rccrdpccl** [comment]
Hi @Zeshan316 . If you get a 403 it probably means you are not sending the correct request, however how to do this would depend on the authentication system your target server is using.

The library provides a basic builder method for building the GraphQL client: `$client = Softonic\GraphQL\ClientBuilder::build($endpoint, $guzzleOptions);`
For example, in case your server is using basic auth, you could set guzzleOptions in a similar fashion to this: `$guzzleOptions = ['auth' => ['username', 'password']]`

However if your server is using oauth2, the library implements a builder method to which you would need to only pass the oauth provider. There is an example in the README (https://github.com/softonic/graphql-client#documentation) and you can find more info about existing oauth providers implementing the `OAuth2Provider` interface at https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md .

**Comment by ceefour** [comment]
For `Bearer` access token, this works for me:

```php
    $client = \Softonic\GraphQL\ClientBuilder::build(
      'https://realm.mongodb.com/api/client/v2.0/app/MY_APP_ID/graphql',
			[
				'headers' => ['Authorization' => "Bearer $access_token"]
			]
    );
```
