### ISSUE TITLE
How to add header for auth?

### ISSUE THREAD

**Issue by yozawiratama** [softonic/graphql-client#39]

**Comment by rccrdpccl** [comment]
You can build a client with an OAuth2 provider, which will negotiate tokens, add token as header, etc, as explained in the readme: https://github.com/softonic/graphql-client#documentation

If unable to do that, you can build your own GraphQL client with your own guzzle instance:
```
return new \Softonic\GraphQL\Client(
           $customGuzzleClient,
            new \Softonic\GraphQL\ResponseBuilder()
        );
```

Under the hood, when building a client with `buildWithOAuth2Provider` method (explained in the readme), it adds a middleware to a vanilla guzzle client using https://github.com/softonic/guzzle-oauth2-middleware/

**Comment by rccrdpccl** [comment]
Any issue please feel free to ask or re-open the issue
