### ISSUE TITLE
Error when submitting Mutation Request

### ISSUE THREAD

**Issue by rizwansaleem70** [softonic/graphql-client#40]
I'm getting an error while submitting Mutation. 

![Screenshot_10](https://user-images.githubusercontent.com/10451770/80988523-0d00be80-8e4d-11ea-8fda-83a66831400b.png)

This is the code.
![Screenshot_9](https://user-images.githubusercontent.com/10451770/80988442-f65a6780-8e4c-11ea-9b84-35019768cfe5.png)

Can anyone tell me what's wrong in my code?

**Comment by joskfg** [comment]
I think the server is telling you to use a named mutation. 

Try with `mutation anyName {`

**Comment by joskfg** [comment]
If you need more help, feel free to re-open it.
