### ISSUE TITLE
Provider Class missing 

### ISSUE THREAD

**Issue by Danoweb** [softonic/graphql-client#5]
Hello, I pulled the project down using composer and copy/pasted the getting started code from the documentation, however I am getting the following error:

`Fatal error: Uncaught Error: Class 'Softonic\OAuth2\Client\Provider\Softonic' not found`

(I am using the composer autoloader to include the files, and other libraries from composer are functioning as expected)

When trying to execute this line:
`$provider = new Softonic\OAuth2\Client\Provider\Softonic($options);`

Please let me know what the fix for this may be,
Thanks!

**Comment by rccrdpccl** [comment]
Hi! The readme uses that class as an example to initialise the GraphQL client with built-in oauth negotiation. If you'd like to do that, you could use any provider that implements League\OAuth2\Client\Provider\AbstractProvider from "league/oauth2-client" package (>= 2.0). Here a few examples: http://oauth2-client.thephpleague.com/providers/league/.

If you would like to instantiate an object of GraphQL client without OAuth2 layer, you could do so following the second example in the readme.

In any case, I think we should update the documentation to make it clearer.

Does this solve your issue?

**Comment by Danoweb** [comment]
Oh! I didn't understand that, with the dependency on league/oauth2 I was working on the assumption it handled the oauth request.  OK I will update my project and report back as to whether that resolved my issue or not.  Thanks!

**Comment by Danoweb** [comment]
That got me up and running I was able to use the generic provider! 

`$provider = new \League\OAuth2\Client\Provider\GenericProvider($options);` 

Thanks! 
(Closing Issue)
