### ISSUE TITLE
how to get cookies from http response? 

### ISSUE THREAD

**Issue by csksaravana** [softonic/graphql-client#57]
Hi,  

I need to get a cookie from the response.  
![image](https://user-images.githubusercontent.com/849683/87266975-0b144500-c4f9-11ea-8d1a-22a90a008999.png)

can you please advise if there is an option to get? we need those cookies from the login call.

Thank you!

**Comment by joskfg** [comment]
The library doesn't support direct access to the original/raw response. It could be improved to be able to access the raw response. PRs are accepted :-).

**Comment by rccrdpccl** [comment]
I think this is not responsibility of this package. At the moment we are handling all auth related stuff in the HTTP client (Guzzle). We support OAuth2, and potentially we could accept other standard auth methods. However, for custom methods I suggest to inject a HTTP Client that can handle it (we have used Guzzle middleware to handle this topic)

Right now we should be able to achieve what you are suggesting by injecting an HTTP client able to inspect last response.

**Comment by csksaravana** [comment]
> The library doesn't support direct access to the original/raw response. It could be improved to be able to access the raw response. PRs are accepted :-).

Noted on this, thank you!

**Comment by csksaravana** [comment]
> I think this is not responsibility of this package. At the moment we are handling all auth related stuff in the HTTP client (Guzzle). We support OAuth2, and potentially we could accept other standard auth methods. However, for custom methods I suggest to inject a HTTP Client that can handle it (we have used Guzzle middleware to handle this topic)
> 
> Right now we should be able to achieve what you are suggesting by injecting an HTTP client able to inspect last response.

Got it, thank you for this support!

**Comment by rccrdpccl** [comment]
Issue closed as not relevant, but please do not hesitate to ask if you have any further doubts.
