### ISSUE TITLE
Guzzlehttp/guzzle version conflict, required  ^6.3, installed ^7.2

### ISSUE THREAD

**Issue by Nemutagk** [softonic/graphql-client#58]
Good day!

I have a problem trying to install the library, it marks a conflict with the composer.json since I have installed version 7.2

> Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires softonic/graphql-client ^1.2 -> satisfiable by softonic/graphql-client[1.2.0].
    - softonic/graphql-client 1.2.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by joskfg** [comment]
Hello @Nemutagk,

Thanks for your issue, addressing it in #59.

**Comment by joskfg** [comment]
Released https://github.com/softonic/graphql-client/releases/tag/1.3.0
