### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by wucdbm** [softonic/graphql-client#60]
Basically, https://packagist.org/packages/softonic/guzzle-oauth2-middleware needs to be upgraded and psr/cache set to ^1|^2|^3 or maybe drop 1 and go with ^2|^3

Then this library needs a bump, and I guess it will be installable.

`composer require softonic/graphql-client` 

Using version ^1.3 for softonic/graphql-client
./composer.json has been updated
Running composer update softonic/graphql-client
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - softonic/guzzle-oauth2-middleware[1.1.0, ..., 1.3] require psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - softonic/graphql-client 1.3.0 requires softonic/guzzle-oauth2-middleware ^1.1 -> satisfiable by softonic/guzzle-oauth2-middleware[1.1.0, ..., 1.3].
    - Root composer.json requires softonic/graphql-client ^1.3 -> satisfiable by softonic/graphql-client[1.3.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require softonic/graphql-client:*" to figure out if any version is installable, or "composer require softonic/graphql-client:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by rccrdpccl** [comment]
Thanks for pointing this out.

Are you interested in sending the necessary pull requests to fix this problem?

**Comment by wucdbm** [comment]
I've migrated to another library.
