### ISSUE TITLE
Question: The proper way to modify the query with PHP variables?

### ISSUE THREAD

**Issue by AnttiTolvanen01** [softonic/graphql-client#63]
This is a question, not an issue. I read the documentation, but didn't find an answer for this one. What would be to suggested method for modifying the query with php variables.
Here's an example (which won't work):

```
$my_additional_parameters = 'extra_foo1
  extra_foo2 {
    more_foo_a
    more_foo_b
  }';

$query = <<<'QUERY'
query GetFooBar($idFoo: String, $idBar: String) {
  foo(id: $idFoo) {
    id_foo
    bar (id: $idBar) {
      id_bar
    }
  $my_additional_parameters
  }
}
QUERY;
```

**Comment by spycheast** [comment]
I believe there is a pretty clear explanation in the main doc.

`$query = <<<'QUERY'
query GetFooBar($idFoo: String, $idBar: String) {
  foo(id: $idFoo) {
    id_foo
    bar (id: $idBar) {
      id_bar
    }
  }
}
QUERY;

$variables = [
    'idFoo' => 'foo',
    'idBar' => 'bar',
];`

In the example above you can use $variables array you can put your php variables to be used in query, e.g.
`$variables = [
    'idFoo' => $myPhpVariable1,
    'idBar' => $myPhpVariable2,
];`

**Comment by spycheast** [comment]
If your question is about how to concatenate nowdoc string, these links might be useful:
https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc
https://stackoverflow.com/questions/4000103/is-it-possible-to-concatenate-heredoc-string-in-php

P.S. Heredoc is pretty much similar to nowdoc, like double quoted string and single quoted string
