### ISSUE TITLE
Using with OAuth2 provider: Access Token URL

### ISSUE THREAD

**Issue by overwise** [softonic/graphql-client#67]
Hi, 
Where does the endpoint for authorisation server goes?
Thanks

**Comment by joskfg** [comment]
Hi,

This package allows you to use [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) adapters for authentication, so the endpoint depends on the adapter that you are using. The adapter could be [custom](https://oauth2-client.thephpleague.com/providers/implementing/) or provided by the library as [official](https://oauth2-client.thephpleague.com/providers/league/) or [third party](https://oauth2-client.thephpleague.com/providers/thirdparty/).

For example, you could use [Google authentication](https://github.com/thephpleague/oauth2-google) with a code like this:

```php
$options = [
    'clientId'     => '{google-client-id}',
    'clientSecret' => '{google-client-secret}',
    'redirectUri'  => 'https://example.com/callback-url',
    'hostedDomain' => 'example.com', // optional; used to restrict access to users on your G Suite/Google Apps for Business accounts
];

$provider = new \League\OAuth2\Client\Provider\Google($options);

//  This config is passed to the getAccessToken method "$provider->getAccessToken($grantType, $options);" and it depends on the oauth provider you are using and its grant.
// Example to use RefreshToken
$grantType = new \League\OAuth2\Client\Grant\RefreshToken();
$refreshToken = 'xxxxxxxx';
$options = ['refresh_token' => $refreshToken];

$config = ['grant_type' => $grantType, $options];

$cache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter();

$client = \Softonic\GraphQL\ClientBuilder::buildWithOAuth2Provider(
    'https://your-domain/graphql',
    $provider,
    $config,
    $cache
);
```
