### ISSUE TITLE
PHP 8.4

### ISSUE THREAD

**Issue by cbepxpa3ym** [softonic/graphql-client#69]
Implicitly nullable parameter types are now deprecated.

Examples:

Deprecated: Softonic\GraphQL\Client::query(): Implicitly marking parameter $variables as nullable is deprecated, the explicit nullable type must be used instead in \vendor\softonic\graphql-client\src\Client.php on line 31

Deprecated: Softonic\GraphQL\ResponseBuilder::__construct(): Implicitly marking parameter $dataObjectBuilder as nullable is deprecated, the explicit nullable type must be used instead in \vendor\softonic\graphql-client\src\ResponseBuilder.php on line 11

Please, fix this.

**Comment by joskfg** [comment]
Hi,

Thank you for bringing this to our attention. Currently, compatibility with PHP 8.4 has not yet been implemented. We plan to address this as soon as we have the necessary bandwidth.

In the meantime, if you'd like to expedite the process, we would greatly appreciate any contributions via a Pull Request. Your support would be invaluable.

Thank you for your understanding and for contributing to the project!

**Comment by joskfg** [comment]
Thanks for fixing it in #70
